### ISSUE TITLE
Linux support checklist

### ISSUE THREAD

**Issue by overfl0** [overfl0/Pythia#39]
# Important note: This list is NOT extensive!
There may be lots of other tasks needed to be done besides those listed below.

# High level-changes

- [x] Basic rvextension function for linux .so
- [x] Figure out non-portable Windows functions used
- [x] Rewrite everything to use cmake/makefiles (instead of VisualStudio sln) [#40]
- [x] List open files (used for running mods discovery)
- [x] Store bundled .py files somewhere (currently stored as DLL resources)
- [x] ~~Use system python installation? (no standalone python available for linux, out of the box)~~
- [x] Ensure pip works correctly and add a script to install requirements
- [x] Double-check the compilation flags (use lto if possible)
- [x] Test everything with special characters in the path
- [x] Add a secret value to force the interpreter rebuild in Github Actions
- [x] Vendor libcrypt.so.1
- [x] Add .so file python checks

# Ad hoc changes required in particular files

## Pythia
- [x] Spdlog codecvt issues
- [x] Figure out the issues with spdlog for 32bits

#### DelayedLoader
- [x] Remove completely

#### dllmain.cpp
- [x] Implement linux shared object

#### EmbeddedPython.cpp
- [x] _wputenv_s / TEXT / min / strncpy_s / _TRUNCATE
- [x] linux paths and executables in DoPythonMagic
- [x] Do not use HMODULE

#### FileHandles.cpp
- [x] Reimplement getOpenFiles()

#### ModsLocation.cpp
- [x] Something with using open and path

#### Paths.cpp
- [x] Reimplement getProgramDirectory
- [x] Reimplement getPythonPath

#### ResourceLoader.cpp
- [x] Reimplement loading resources from disk
- [x] Implement storing resources elsewhere

#### rvextension.cpp
- [x] strncpy_s / min / _TRUNCATE
- [x] Correctly export functions for the .so file

#### SQFWriter.cpp
- [x] _CVTBUFSIZE

#### dllmain.cpp:
- [x] tchar include
- [x] strncpy_s / min / _TRUNCATE
- [x] SetDllDirectory - research rpath
- [x] Implement linux shared object

#### PythiaTester.cpp
- [x] __stdcall / _strdup / sprintf_s
- [x] Loading and executing linux shared objects
